<<<<<<< HEAD
# Generated by Django 2.1.7 on 2019-11-20 09:20
=======
# Generated by Django 2.2.5 on 2019-11-07 04:19
>>>>>>> origin/master

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('summary', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
>>>>>>> origin/master
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='#')),
                ('address', models.CharField(default='', max_length=200)),
<<<<<<< HEAD
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
=======
                ('location', models.CharField(default='0,0', max_length=200)),
>>>>>>> origin/master
                ('price', models.FloatField(default=0.0)),
                ('categories', models.CharField(default='', max_length=200)),
                ('summary', models.CharField(default='', max_length=200)),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='LonLatField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
>>>>>>> origin/master
    ]
