# Generated by Django 2.1.7 on 2019-11-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='#')),
                ('address', models.CharField(default='', max_length=200)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('categories', models.CharField(default='', max_length=200)),
                ('summary', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
