# Generated by Django 2.1.7 on 2019-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='summary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
